# Generate the build-only GIF provider-key header from the environment.
#
# Invoked with `cmake -P` from the top-level configure step:
#   cmake -DOUTPUT_DIR=<build>/generated -DREQUIRE_KEYS=<ON|OFF>
#         -P cmake/GenerateGifBuildKeys.cmake
#
# It reads the key VALUES only from the environment variables
#   LIGHTNING_BUILD_GIPHY_API_KEY
#   LIGHTNING_BUILD_KLIPY_API_KEY
# so they never appear on a command line, in CMakeCache.txt, or in build logs.
# The values are never printed; only presence is reported. The generated header
# lives solely in the build tree, is never tracked, installed, or packaged, and
# an empty value behaves exactly like no embedded key.

if(NOT DEFINED OUTPUT_DIR)
    message(FATAL_ERROR "GenerateGifBuildKeys: OUTPUT_DIR is required")
endif()

set(_giphy "$ENV{LIGHTNING_BUILD_GIPHY_API_KEY}")
set(_klipy "$ENV{LIGHTNING_BUILD_KLIPY_API_KEY}")

# Trim accidental surrounding whitespace; empty then means "no embedded key".
string(STRIP "${_giphy}" _giphy)
string(STRIP "${_klipy}" _klipy)

if(REQUIRE_KEYS)
    if(_giphy STREQUAL "" OR _klipy STREQUAL "")
        # Do not reveal which is set beyond a generic presence line elsewhere.
        message(FATAL_ERROR
            "Official release build requires both GIPHY and KLIPY provider keys")
    endif()
endif()

# Escape for a C string literal (backslash and double-quote only; whitespace
# such as newlines has already been stripped).
string(REPLACE "\\" "\\\\" _giphy_esc "${_giphy}")
string(REPLACE "\"" "\\\"" _giphy_esc "${_giphy_esc}")
string(REPLACE "\\" "\\\\" _klipy_esc "${_klipy}")
string(REPLACE "\"" "\\\"" _klipy_esc "${_klipy_esc}")

file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(_header "${OUTPUT_DIR}/LightningGifBuildKeys.h")
set(_tmp "${_header}.tmp")

file(WRITE "${_tmp}"
"// Generated by cmake/GenerateGifBuildKeys.cmake. Do not edit or commit.\n"
"// Build-only GIF provider keys. Never installed, packaged, or logged.\n"
"#pragma once\n"
"#define LIGHTNING_GIF_BUILD_GIPHY_KEY \"${_giphy_esc}\"\n"
"#define LIGHTNING_GIF_BUILD_KLIPY_KEY \"${_klipy_esc}\"\n")

# Atomic replace so a partially written header is never compiled.
file(RENAME "${_tmp}" "${_header}")

# Restrictive permissions where the platform supports it.
if(NOT WIN32)
    file(CHMOD "${_header}" PERMISSIONS OWNER_READ OWNER_WRITE)
endif()

# Presence-only reporting; never the value, length, or any fragment.
if(NOT _giphy STREQUAL "")
    message(STATUS "GIPHY release key present")
endif()
if(NOT _klipy STREQUAL "")
    message(STATUS "KLIPY release key present")
endif()

# Drop local references to the values immediately.
unset(_giphy)
unset(_klipy)
unset(_giphy_esc)
unset(_klipy_esc)
